name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 3.89.115.59
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd LearningDevOps
            git pull
            pnpm i
            pnpm run build
            pm2 restart web
            pm2 restart http-server
            pm2 restart ws-server
            
            nohup pnpm run start > app.log 2>&1 &
            echo "Deployment successful"
