name: Deploy to Staging


on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Staging Server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -tt ubuntu@3.89.115.59 "
            cd LearningDevOps/ &&
            git pull origin main &&
            export PATH=/root/.nvm/versions/node/v22.13.1/bin:$PATH &&
            npm install -g pnpm &&
            pnpm install &&
            pnpm run build &&
            pm2 restart web &&
            pm2 restart http-server &&
            pm2 restart ws-server
          "
